version: '3.8'

services:
  service:
    container_name: event-ingestor-service
    command: run
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./target:/code/target
      - ./src:/code/src
      - ./Cargo.toml:/code/Cargo.toml